### ISSUE TITLE
Dotnet publish doesn't work

### ISSUE THREAD

**Issue by codehippie1** [based-ghost/aspnet-core-react-redux-playground-template#4]
Publishing this template as is does not produce the dist/ClientApp folder. The resulting published artifacts cant be run or deployed to IIS

**Comment by based-ghost** [comment]
@codehippie1 - I can try and run through the process myself when I have time, but maybe this issue outlined in this stackoverflow thread may be of some help? Also, you may want to pull down the latest version of the code as I just did a large refactor/update to the codebase.

https://stackoverflow.com/questions/61503211/having-trouble-deploying-reactjs-and-net-4-8-backend-to-iis-dist-folder-missi

**Comment by based-ghost** [comment]
Closing for now.
