### ISSUE TITLE
npm install hangs 

### ISSUE THREAD

**Issue by jackyshang** [based-ghost/aspnet-core-react-redux-playground-template#5]
![image](https://user-images.githubusercontent.com/5872867/141885157-0a5cb2b5-104c-4023-a3ce-2b6eeb13e5a9.png)

npm install seems like hanging there while nodejs process shows CPU at 14%. I am using Node 14 with npm 8.1.3, also I have tried to use Node 16(npm 8.1.3) as well as Node 15(npm 7) none of them worked.

**Comment by based-ghost** [comment]
@jackyshang - looking at your node/npm combos listed - Node 14.x.x and npm 8.1.3 looks like it could be the issue as that version of npm looks to be a few versions ahead of what is recommended for that version of node. I just tried using node 14.18.1 and npm 6.14.15 and had no issues. I'd recommend deleting `node_modules` dir and `package-lock.json` and retrying the `npm install` using that combination.

**Comment by based-ghost** [comment]
Another potential workaround for similar issues is to use commands `npm install --force` or `npm install --legacy-peer-deps`
